### ISSUE TITLE
Rollback updates and cron style jobs

### ISSUE THREAD

**Issue by kkrishna** [rdelval/gorealis#2]
1) When an update is aborted, configuration doesn't rollback to previous state -- say that update was to increase instance count from 1 to 5 and it was aborted when instance count reached 4. It doesn't rollback to previous instance count of 1.

2) Also add support for scheduling cron-style jobs. 

thanks.

**Comment by mbdas** [comment]
For 1 the right parameter has to be set

**Comment by rdelval** [comment]
In testing that function we've found out that the rollback parameter is only true if the update fails, but not unfortunately if it's explicitly aborted.

**Comment by mbdas** [comment]
What does abort mean in this context?  Abort is not a failure? Scheduler aborting? Thx

**Comment by rdelval** [comment]
In this context it's when we send another thrift api call telling the scheduler to stop the update immediately. (https://github.com/rdelval/gorealis/blob/master/auroraAPI.thrift#L1103)

**Comment by mbdas** [comment]
Ok that behavior is as per documented. So not an issue.
http://aurora.apache.org/documentation/latest/features/job-updates/

**Comment by rdelval** [comment]
Yep! It's in line with how it's supposed to work. We should reword 1 to say support for the new `rollbackJobUpdate` api that will be available in 0.16.0 https://github.com/apache/aurora/blob/master/api/src/main/thrift/org/apache/aurora/gen/api.thrift#L1123

**Comment by kkrishna** [comment]
yep #1, is inline with new rollbackJobUpdate functionality.

**Comment by rdelval** [comment]
rollback API and schedule, deschedule, and start cron APIs have been added, please test them.

**Comment by rdelval** [comment]
Fixed in 15c2472ffd5ee6997d9ae66b58eccdf1bfe3d822 
Closing this, please re-open if there's any issues.
