### ISSUE TITLE
gorealis config refactor

### ISSUE THREAD

**Issue by kkrishna** [rdelval/gorealis#24]
@rdelval ..Per our earlier conversation, this is the attempt..

The commit is in my fork: https://github.com/kkrishna/gorealis/commit/b10df0603e8e9c696d04de0e0554d8911c253f1b

Basically, with this change, to get a gorealis handle using, NewRealisClient api with variadic input options as follows: 
r, err = realis.NewRealisClient(realis.ZKCluster(cluster), realis.BasicAuth(*username, *password), realis.ThriftJSON(), realis.TimeoutMS(15000))
 
r, err = realis.NewRealisClient(realis.SchedulerUrl(*url), realis.BasicAuth(*username, *password), realis.ThriftJSON(), realis.TimeoutMS(20000), realis.BackOff(defaultBackoff))

Pls. go through the code in my fork.  Existing Default*APIs for client can be deprecated later. Will raise PR tomorrow after testing is complete. thanks.

**Comment by rdelval** [comment]
Should we close this since the changes are in for the new config approach?

**Comment by kkrishna** [comment]
this can be closed.. we can have a separate one for deprecating some apis.
