### ISSUE TITLE
Add Support to create a Job to run container types

### ISSUE THREAD

**Issue by smothiki** [rdelval/gorealis#5]
Right now the data structure are defines in thrift to accept containers. But there are no proper methods to modify the Taskconfig or Job struct.

**Comment by rdelval** [comment]
You are indeed correct. Unfortunately, gorealis only supports a subset of all that the bundled client is capable of. It would be a much welcome contribution to be able to start jobs with containers.

**Comment by smothiki** [comment]
I'm thinking of contributing this feature. Opened this just to keep track of it.

**Comment by rdelval** [comment]
Apologies for taking over this but I needed it for a personal project. Added in 66a2868aabbce6eb2d33b17b4bf285ddbfa6b82f.

**Comment by rdelval** [comment]
Initial support added in 51699eda4e86b26dc95de0610b24a9648a97a3a0
