### ISSUE TITLE
Nil error object returned from gorealis api for error scenarios

### ISSUE THREAD

**Issue by kkrishna** [rdelval/gorealis#7]
Nil error object returned from gorealis api error scenarios. this behavior is for both  thermos and custom executor.

Purposefully set ram to 0 to generate error scenario ...

**log for custom executor:**
/usr/local/go/bin/go build -o /private/var/folders/jc/ljm2qnwx42l8f88vnxtt6k_82zcfdr/T/customCreatego /Users/kkrishna/work/golang/src/github.com/rdelval/gorealis/examples/client.go
Creating job
**error obj: <nil>**
response: Response({ResponseCode:INVALID_REQUEST Result_:<nil> ServerInfo:ServerInfo({ClusterName:aurora-cluster StatsUrlPrefix:}) Details:[ResponseDetail({Message:ram_mb must be greater than 0.0})]})Process finished with exit code 0

**thermos logs:**

/usr/local/go/bin/go build -o /private/var/folders/jc/ljm2qnwx42l8f88vnxtt6k_82zcfdr/T/thermosCreatego /Users/kkrishna/work/golang/src/github.com/rdelval/gorealis/examples/client.go
Creating job
**error obj: <nil>**
response: Response({ResponseCode:INVALID_REQUEST Result_:<nil> ServerInfo:ServerInfo({ClusterName:aurora-cluster StatsUrlPrefix:}) Details:[ResponseDetail({Message:ram_mb must be greater than 0.0})]})

Process finished with exit code 0

**Comment by rdelval** [comment]
Fixed in a715282c00918986f5af48dc31c7986247d75283. Please reopen if the fix doesn't work as expected.
